export const products = [
  {
    id: 1,
    name: "กระเป๋าเป้สายแฟชั่น",
    category: "แฟชั่น",
    price: 490,
    originalPrice: 690,
    image:
      "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=700&q=80",
    description: "กระเป๋าเป้ดีไซน์สวย เหมาะสำหรับใช้งานทุกวัน",
    rating: 4.8,
    sold: 1240,
    badge: "ขายดี",
    shipping: "ส่งฟรี",
  },
  {
    id: 2,
    name: "หูฟังไร้สาย",
    category: "อิเล็กทรอนิกส์",
    price: 1290,
    originalPrice: 1590,
    image:
      "https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=700&q=80",
    description: "เสียงคมชัด พร้อมแบตเตอรี่ใช้งานนาน",
    rating: 4.9,
    sold: 980,
    badge: "แนะนำ",
    shipping: "ส่งฟรี",
  },
  {
    id: 3,
    name: "นาฬิกาข้อมือสปอร์ต",
    category: "กีฬา",
    price: 860,
    originalPrice: 1120,
    image:
      "https://images.unsplash.com/photo-1519241047957-be31d7379a5d?auto=format&fit=crop&w=700&q=80",
    description: "นาฬิกาเท่ ๆ สำหรับชีวิต Active",
    rating: 4.7,
    sold: 760,
    badge: "ลดแรง",
    shipping: "ส่งฟรี",
  },
  {
    id: 4,
    name: "ชุดทำความสะอาดบ้าน",
    category: "ไลฟ์สไตล์",
    price: 560,
    originalPrice: 780,
    image:
      "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=700&q=80",
    description: "อุปกรณ์ครบชุดเพื่อการทำความสะอาดได้ง่าย",
    rating: 4.6,
    sold: 540,
    badge: "ใหม่",
    shipping: "ส่งฟรี",
  },
  {
    id: 5,
    name: "รองเท้าวิ่งเพื่อสุขภาพ",
    category: "กีฬา",
    price: 1490,
    originalPrice: 1890,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80",
    description: "รองเท้ารองรับแรงกระแทกสำหรับการวิ่งระยะสั้น",
    rating: 4.8,
    sold: 640,
    badge: "ยอดนิยม",
    shipping: "ส่งฟรี",
  },
  {
    id: 6,
    name: "แก้วน้ำเก็บความเย็น",
    category: "ไลฟ์สไตล์",
    price: 340,
    originalPrice: 450,
    image:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=700&q=80",
    description: "แก้วน้ำเย็นนาน เหมาะสำหรับพกพา",
    rating: 4.5,
    sold: 430,
    badge: "มาใหม่",
    shipping: "ส่งฟรี",
  },
  {
    id: 7,
    name: "โคมไฟตั้งโต๊ะมินิมอล",
    category: "บ้านและครัว",
    price: 790,
    originalPrice: 990,
    image:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80",
    description: "โคมไฟแสงนุ่ม ปรับบรรยากาศโต๊ะทำงานและห้องนอน",
    rating: 4.7,
    sold: 385,
    badge: "ใหม่",
    shipping: "ส่งฟรี",
  },
  {
    id: 8,
    name: "เครื่องบดกาแฟมือหมุน",
    category: "บ้านและครัว",
    price: 650,
    originalPrice: 850,
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&q=80",
    description: "บดเมล็ดกาแฟสดได้ละเอียด พร้อมใช้งานทุกเช้า",
    rating: 4.8,
    sold: 298,
    badge: "แนะนำ",
    shipping: "ส่งฟรี",
  },
  {
    id: 9,
    name: "คีย์บอร์ดไร้สายแบบบาง",
    category: "อุปกรณ์ทำงาน",
    price: 990,
    originalPrice: 1290,
    image:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=700&q=80",
    description: "คีย์บอร์ดเสียงเงียบ ดีไซน์บาง เหมาะกับโต๊ะทำงานยุคใหม่",
    rating: 4.6,
    sold: 512,
    badge: "ขายดี",
    shipping: "ส่งฟรี",
  },
  {
    id: 10,
    name: "ขาตั้งโน้ตบุ๊กอะลูมิเนียม",
    category: "อุปกรณ์ทำงาน",
    price: 590,
    originalPrice: 790,
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=700&q=80",
    description: "ยกหน้าจอให้อยู่ในระดับสายตา ช่วยจัดโต๊ะให้เป็นระเบียบ",
    rating: 4.8,
    sold: 447,
    badge: "ยอดนิยม",
    shipping: "ส่งฟรี",
  },
  {
    id: 11,
    name: "เซรั่มบำรุงผิวหน้า",
    category: "ความงาม",
    price: 520,
    originalPrice: 690,
    image:
      "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=700&q=80",
    description: "เซรั่มเนื้อบางเบา เติมความชุ่มชื้นให้ผิวดูสดใส",
    rating: 4.7,
    sold: 824,
    badge: "ขายดี",
    shipping: "ส่งฟรี",
  },
  {
    id: 12,
    name: "ชุดแปรงแต่งหน้า 8 ชิ้น",
    category: "ความงาม",
    price: 450,
    originalPrice: 620,
    image:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=700&q=80",
    description: "แปรงขนนุ่มครบชุดสำหรับแต่งหน้าในทุกวัน",
    rating: 4.6,
    sold: 610,
    badge: "ลดแรง",
    shipping: "ส่งฟรี",
  },
  {
    id: 13,
    name: "กระเป๋าเดินทางล้อลาก",
    category: "การเดินทาง",
    price: 1890,
    originalPrice: 2490,
    image:
      "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=700&q=80",
    description:
      "กระเป๋าเดินทางน้ำหนักเบา ล้อหมุนคล่อง พร้อมช่องจัดเก็บหลายแบบ",
    rating: 4.8,
    sold: 356,
    badge: "คุ้มค่า",
    shipping: "ส่งฟรี",
  },
  {
    id: 14,
    name: "หมอนรองคอเมมโมรี่โฟม",
    category: "การเดินทาง",
    price: 390,
    originalPrice: 520,
    image:
      "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80",
    description: "รองรับต้นคออย่างนุ่มสบาย เหมาะสำหรับเดินทางไกล",
    rating: 4.5,
    sold: 274,
    badge: "มาใหม่",
    shipping: "ส่งฟรี",
  },
  {
    id: 15,
    name: "ชุดชาเขียวมัทฉะพรีเมียม",
    category: "อาหารและเครื่องดื่ม",
    price: 480,
    originalPrice: 590,
    image:
      "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=700&q=80",
    description: "มัทฉะหอมละมุนสำหรับชงดื่มหรือทำเมนูโปรดที่บ้าน",
    rating: 4.9,
    sold: 731,
    badge: "แนะนำ",
    shipping: "ส่งฟรี",
  },
  {
    id: 16,
    name: "กราโนล่าธัญพืชรวม",
    category: "อาหารและเครื่องดื่ม",
    price: 290,
    originalPrice: 360,
    image:
      "https://images.unsplash.com/photo-1517093728432-a0440f8d45af?auto=format&fit=crop&w=700&q=80",
    description: "กราโนล่ากรอบอร่อย อุดมด้วยธัญพืชสำหรับมื้อเช้าที่ง่ายขึ้น",
    rating: 4.6,
    sold: 489,
    badge: "สุขภาพดี",
    shipping: "ส่งฟรี",
  },
  {
    id: 17,
    name: "ชั้นวางต้นไม้ไม้ไผ่",
    category: "บ้านและครัว",
    price: 880,
    originalPrice: 1150,
    image:
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=700&q=80",
    description: "ชั้นวางดีไซน์อบอุ่น เพิ่มพื้นที่สีเขียวให้มุมโปรดของคุณ",
    rating: 4.7,
    sold: 198,
    badge: "แต่งบ้าน",
    shipping: "ส่งฟรี",
  },
  {
    id: 18,
    name: "ลำโพงบลูทูธพกพา",
    category: "อิเล็กทรอนิกส์",
    price: 1090,
    originalPrice: 1390,
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=80",
    description: "เสียงเต็มคมชัด แบตเตอรี่อึด พร้อมพกเพลงไปได้ทุกที่",
    rating: 4.8,
    sold: 905,
    badge: "ยอดนิยม",
    shipping: "ส่งฟรี",
  },
];
